# Generated by Django 4.0.5 on 2022-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(blank=True, default='Default reviewer', max_length=255, null=True)),
                ('movie', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True, default='Default content', null=True)),
            ],
        ),
    ]
